server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: school-app-backend
  
  # Database Configuration (Supabase PostgreSQL)
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
      initialization-fail-timeout: -1  # Don't fail startup if DB unavailable
  
  jpa:
    hibernate:
      ddl-auto: none  # We manage schema manually
    show-sql: true  # Enable SQL logging for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

# Supabase Configuration
supabase:
  url: ${SUPABASE_URL:https://your-project.supabase.co}
  service-key: ${SUPABASE_SERVICE_KEY:your-service-key}
  anon-key: ${SUPABASE_ANON_KEY:your-anon-key}

logging:
  level:
    com.educollab: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG  # Show SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Show parameter values
    org.hibernate: WARN
    root: INFO
